
spring.profiles.active: dev

profile: profile

---
spring.profiles: dev
profile: dev from config remote

---
spring.profiles: prod
profile: prod from config remote

---
spring.profiles: test
profile: test from config remote

